config/routes.rb
Rails.application.routes.draw do

  get 'today' => 'activity_handler#today'
  get 'toggle/:id' => 'activity_handler#toggle'
  get 'week' => 'activity_handler#week'
  get 'overview' => 'activity_handler#overview'
  resources :activity_handler

  resources :users
  resources :sessions
  resources :friendships

  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "feed" => "users#feed", :as => "feed"

  root 'activity_handler#today'
  

end

app/models/activity_handler.rb
# This class bridges the Activity framework to the user. Each user has one activity handler.

class ActivityHandler < ActiveRecord::Base
  include MyModules

  # Constants that define type_id
  FULL_TASK = 0
  PARTIAL_TASK = 1
  HABIT = 2
  HABIT_NUMBER = 3
  HABIT_WEEK = 4
  GOAL = 5
  PROGRESS_SUM = 6
  PROGRESS_AVG = 7
  PROGRESS_MAX = 8
  
  # Returns the activity specified by id
  def find_act(id, current_user)
    return current_user.activities.find(id)
  end

  # Uses the module to create the activity
  def create_activity(params, current_user)
    act_type = activity_type(params) # gets what type of activity it is
    return ActivityHelper.create_activity(act_type, params, current_user)

  end

  # Uses the module to check for errors
  def check_form_errors(params, update = false)
    params[:habit_type] = 'none'
    act_type = activity_type(params)
    return ActivityHelper.form_errors(act_type, params, update)
  end

  # Determines what type of activity it should be based on the params
  def activity_type(params)
    type_group_id = params[:type_group]
    case TypeGroup.find(type_group_id).name
    when 'Basic Task'
      if params[:internal] == 1.to_s 
        return FULL_TASK
      else
        return PARTIAL_TASK
      end
    when 'Habit'
      case params[:habit_type]
      when 'none'
        return HABIT
      when 'number'
        return HABIT_NUMBER
      when 'week'
        return HABIT_WEEK
      else
        Rails.logger.debug "invalid habit type"
        return nil
      end
    when 'Goal'
      # incomplete
      Rails.logger.debug "Goal creation not yet complete"
      return nil
    else
      Rails.logger.debug "Invalid TypeGroup"
      return nil
    end
  end

  # Gets activities that can be parents - incomplete or overdue
  def get_parentable(current_user)
    activities = get_activities(current_user)
    
    return activities.where("(state is ? OR state is ?) AND rep_parent_id is ?", Activity::INCOMPLETE, Activity::OVERDUE, nil)
    
  end

  # Takes an id and returns an array of activity ids that are the id or are children.
  # This is to ensure, when editing, an activity isn't its own parent
  def it_and_children(id, current_user)
    it_children = [ ] 
    it_children << (id)
    activities = get_activities(current_user)
    act = activities.find(id)
    act.children.each{ |child| it_children << it_and_children(child.id) }
    act.rep_parent_id.nil? ? nil : it_children << act.rep_parent_id
    return it_children
  end

  # Toggles the state of the activity. If it is complete, calls incomplete, if incomplete or
  # overdue calls complete
  def toggle(id, current_user)
    activities = get_activities(current_user)
    activity = activities.find(id)
    state = activity.state
    if state == Activity::COMPLETE
      activity.incomplete
      if activity.report_to == Activity::FOLLOWERS or activity.report_to == Activity::BOTH
        current_user.feed_items.create(:message => 
                                       "actually didn't complete #{activity.name}")
      end
      return "Set #{activity.name} to incomplete..."
    elsif state == Activity::INCOMPLETE or Activity::OVERDUE
      activity.complete
      if activity.report_to == Activity::FOLLOWERS or activity.report_to == Activity::BOTH
        current_user.feed_items.create(:message => 
                                       "completed #{activity.name}")
      end
      return "Completed #{activity.name}!"
    end
  end

  # Gets activities that should be shown today - complete, incomplete, and overdue
  def get_today(current_user)
    activities = get_activities(current_user)
    today = { }
    today[:complete] = activities.
      where("state is ? AND show_date is ?", 
            Activity::COMPLETE, Date.current)
    today[:incomplete] = activities.
      where("state is ? AND show_date is ?", 
            Activity::INCOMPLETE, Date.current)
    today[:overdue] = activities.
      where("state is ?", 
            Activity::OVERDUE)
    return today
  end

  # Updates the activity based on what type it is
  def update_act(params, current_user)
    activities = get_activities(current_user)
    set_rewards = current_user.set_rewards
    old_act = activities.find(params[:id])
    
    # tasks
    if old_act.class == FullTask or old_act.class == PartialTask
      # set the name, desc, show_date, expiration_date, reward, and penalty
      old_act.name = params[:name]
      old_act.description = params[:description]
      old_act.show_date = params[:show_date]
      old_act.expiration_date = params[:expiration_date]
      old_act.report_to = params[:report_to]
      if set_rewards
        old_act.reward = params[:reward]
        old_act.penalty = params[:penalty]
      end
      old_act.save!
      
      # if parent changed, makes sure it a valid change and change it
      parent_id = params[:parent_id].to_i
      if !params[:parent_id].empty? and parent_id != old_act.parent_id
            handler = current_user.activity_handler
            it_and_child = handler.it_and_children(old_act.id)
            if !it_and_child.include?(parent_id)
              parent = Activity.find(parent_id)
              parent.add_child(old_act)
            end
      end

    # habits
    elsif old_act.class == Habit or old_act.class == HabitNumber or 
        old_act.class == HabitWeek
      
      # if not a rep_parent then don't need to change expiration_date of the whole habit
      expire = true
      if !old_act.rep_parent.nil?
        old_act.show_date = params[:show_date]
        old_act.expiration_date = params[:expiration_date]
        old_act.save!
        old_act = old_act.rep_parent
        expire = false
      end


      # change the name, desc, reward, penalty
      old_act.name = params[:name]
      old_act.description = params[:description]
      old_act.report_to = params[:report_to]
      if set_rewards
        old_act.reward = params[:reward]
        old_act.penalty = params[:penalty]
      end
      old_act.save!
      
      # change it for the reps as well
      
      old_act.repititions.each do |rep|
        rep.name = params[:name]
        rep.description = params[:description]
        rep.report_to = params[:report_to]
        if set_rewards
          rep.reward = params[:reward]
          rep.penalty = params[:penalty]
        end
        rep.save!
      end

      
      # if repeated changed, delete future reps and create new ones
      gen = false
      repeated = params[:repeated].keys.to_a.collect { |d| d.to_i }
      if repeated != old_act.get_repeated
        old_act.del_reps
        old_act.set_repeated(repeated)
        gen = true
      end

      # if expiration date changed, delete future reps
      if expire and old_act.expiration_date != params[:expiration_date]
        old_act.del_reps
        old_act.expiration_date = params[:expiration_date]
        gen = true
      end

      old_act.save!
      
      # generate new reps if needed
      if gen
        if old_act.expiration_date.nil?
          handler = current_user.activity_handler
          old_act.gen_reps(Date.tomorrow, handler.upto_date)
        else
          old_act.gen_reps(Date.tomorrow, old_act.expiration_date)
        end
        old_act.reload
        old_act.repititions.each { |rep| current_user.activities << rep }
      end
      
      # if parent changed, make sure it valid and change it
      parent_id = params[:parent_id].to_i
      if params[:parent_id].empty? 
        old_act.make_root
      elsif parent_id != old_act.parent_id
            handler = ActivityHandler.find(1)
            it_and_child = handler.it_and_children(old_act.id)
            if !it_and_child.include?(parent_id)
              parent = Activity.find(parent_id)
              parent.add_child(old_act)
            end
      end
    end
  end

  # calls remove_act on the activity
  def remove_act(id, current_user)
    activity = get_activities(current_user).find(id)
    activity.remove_act
    if activity.is_a? (Habit) and (activity.report_to == Activity::FOLLOWERS or 
                                   activity.report_to == Activity::BOTH)
      current_user.feed_items.create(:message => 
                                     "gave up on the habit #{activity.name}")
    end
    return "Removed #{activity.name}!"
  end

  # gets the activities that are assigned for each day of the week
  def week(date, week_begin, current_user)
    activities = get_activities(current_user)
    days = {}
    if date == "this_week"
      date = Date.current
    else
      begin
        date = Date.parse(date)
      rescue
        date = Date.current
      end
    end

    # get the beginning of the week
    first_date = date.
      beginning_of_week(start_date = week_begin)

    # go through each day of the week and get the activities
    for i in 0..6
      add_date= first_date.advance(:days => i)
      acts = activities.where(:show_date => add_date)
      days[add_date] = acts
    end

    return days
  end

  # Returns activities that are root. The all parameter determines whether to get all or just,
  # incomplete/overdue.
  def roots(all = false, current_user)
    if all
      return get_activities(current_user).where("rep_parent_id is ? AND is_root is ?", nil, true)
    else 
      return get_activities(current_user).where("rep_parent_id is ? AND (state is ? OR state is ?) AND is_root is ?",
                            nil, Activity::INCOMPLETE, Activity::OVERDUE, true)
    end
  end

  # Gets the attributes of a certain activity and puts them in a format that allows the 
  # forms to preset their data when editing an activity
  def get_attributes(params, current_user)
    act = get_activities(current_user).find(params[:id]) # get the activity

    # Check what type it is
    if act.class == FullTask or act.class == PartialTask
      values = act.attributes.symbolize_keys # make the stings symbols
      values[:type_group] = 1
      return values 

app/controllers/activity_handler_controller.rb
# Each user has an ActivityHandler and it is through the handler that all CRUD operations are
# preformed. This allows us to take the logic out of both the User class and Activity class 
# and keep it as its own seperate entity. 

class ActivityHandlerController < ApplicationController
  include SessionsHelper

  before_action :signed_in_user
  before_action :activity_not_in_past, only: [:edit, :update, :toggle]
  before_action :can_edit, only: [:edit, :update, :destroy]

  # Creating a new activity
  def new
    handler = current_user.activity_handler
    @activities = handler.get_parentable(current_user)
    @errors = { }
    @values = { :show_date => Date.current, :habit_type => 'none', :period => 2,
      :type_group => 1, :report_to => 0} # set some defaults
    @method = :post
    @path = '/activity_handler'   
  end
  
  def create
    handler = current_user.activity_handler

    # create the activity, if there is a new_act there were no errors
    @errors = handler.create_activity(params, current_user)

    respond_to do |format|
      if !@errors[:new_act].nil?
        format.html { redirect_to :action => "today", notice: "Created task" }
        format.js {}
      else
        format.html {
          # there were errors, prep to render the form again
          @values = params
          if @values[:habit_type].nil?
            @values[:habit_type] = 'none'
          end
          @activities = handler.get_parentable(current_user)
          @method = :post
          @path = '/activity_handler'
          render 'new'
        }
        format.js {}
      end 
    end
  end

  # Shows the details of an activity
  def show
    handler = current_user.activity_handler
    @activity = handler.find_act(params[:id], current_user)
  end

  # Shows the activities for the day
  def today
      handler = current_user.activity_handler
      today = handler.get_today(current_user)
      @complete = today[:complete]
      @incomplete = today[:incomplete]
      @overdue = today[:overdue]
      # get the weekly payout
      @week_payout = 0
      handler.roots(true, current_user).each {|act| @week_payout += handler.get_week_reward(act, Date.current) }
  end

  # Redirect to today
  def index
    redirect_to :action => "today"
  end

  # For changing the state of an activity
  def toggle
    handler = current_user.activity_handler
    @notice = handler.toggle(params[:id], current_user)
    
    respond_to do |format|
      format.html {
        redirect_to :action => "today", :notice => @notice
      }
      format.js {}
    end
  end

  # For removing activities
  def destroy
    handler = current_user.activity_handler
    @notice = handler.remove_act(params[:id], current_user)

    respond_to do |format|
      format.html {
        flash[:notice] = @notice
        redirect_to :action => "today"
      }
      format.js {}
    end
  end

  # For editing activities
  def edit
    handler = current_user.activity_handler
    @activities = handler.get_parentable(current_user)
      .where.not(:id => handler.it_and_children(params[:id], current_user))
    @errors = { }
    @values = handler.get_attributes(params, current_user)
    @method = :patch
    @path = "/activity_handler/#{params[:id]}"
  end

  def update
    handler = current_user.activity_handler
    @errors = handler.check_form_errors(params, true)
    if !@errors.empty?
      @values = params
      @activities = handler.get_parentable(current_user)
        .where.not(:id => handler.it_and_children(params[:id], current_user))
      @method = :patch
      @path = "/activity_handler/#{params[:id]}"
      render 'edit'
    else
      handler.update_act(params, current_user)
      redirect_to :action => "today"
    end
  end

  # Displays activities of the week
  def week
    handler = current_user.activity_handler
    if params[:date].nil?
      redirect_to :action => "week", :date => 'this_week'
    else
      handler = current_user.activity_handler
      @days = handler.week(params[:date], :monday, current_user)
    end
  end

  # Structure of the chld/parent relationships
  def overview
      handler = current_user.activity_handler
      @roots = handler.roots(true, current_user)
  end

  private
    # before filters
    def signed_in_user
      store_location
      redirect_to log_in_path, :notice => "Sign in required." unless signed_in?
    end

    def activity_not_in_past
      act = current_user.activity_handler.find_act(params[:id], current_user)
      return redirect_to activity_handler_path, :notice => "Can't edit a past task" unless act.show_date >= Date.current
    end

    def can_edit
      redirect_to activity_handler_path, :notice => "You don't have permission to edit" unless current_user.permissions.where("activity_id is ?", params[:id])[0].can_edit?
    end
end

app/helpers/activity_handler_helper.rb
module ActivityHandlerHelper
end

app/views/activity_handler/_edit_form.html.erb
<%= render 'errors' %>

<div id="activity_nav">
  <div class=<%= @values[:type_group].to_i == 1 ? "shown_form" : "hidden_form" %>>Task</div>
  <div class=<%= @values[:type_group].to_i == 2 ? "shown_form" : "hidden_form" %>>Habit</div>
</div></br>

<%= render 'task_edit_form' %>

<%= render 'habit_edit_form' %>

app/views/activity_handler/_errors.html.erb
<% if !@errors.empty?  %>
  <div id="error_explaination">
  <h2><%= pluralize(@errors.count, "error") %> 
      prohibited this activity from being saved:</h2>
    <ul>
      <% @errors.each do |k,v| %>
        <li><%= v %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/activity_handler/_form.html.erb
<%= render 'errors' %>

<div id="activity_nav">
  <div id="task", class=<%= @values[:type_group].to_i == 1 ? "shown_form_title" : "hidden_form_title" %>>Task</div>
  <div id="habit", class=<%= @values[:type_group].to_i == 2 ? "shown_form_title" : "hidden_form_title" %>>Habit</div>
</div></br>

<%= render 'task_form' %>

<%= render 'habit_form' %>

app/views/activity_handler/_habit_edit_form.html.erb
<%= form_tag(@path, method: @method, id: 'habit_form', class: @values[:type_group].to_i == 2 ? 'shown_form' : 'hidden_form') do %>
  <%= @values[:is_rp] ? "Editing all repititions" : "All changes except show date and expire date will apply to all repititions" %></br></br>
  <%= label_tag 'name', 'Habit Name' %><br>
  <%= text_field_tag 'name', @values[:name] %></br></br>
  <%= label_tag 'description', 'Habit Description' %><br>
  <%= text_area_tag 'description', @values[:description] %></br></br>
  <%= label_tag 'repeated', 'Days to Repeat' %><br>
  <% if @values[:repeated].nil?
       @values[:repeated] = []
     end
     days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
     days.map.with_index do |d, i| %>
    <%= check_box_tag 'repeated[]', i, @values[:repeated].include?(i.to_s) %>
    <%= label_tag 'repeated[]', d %>
  <% end %></br></br>
  <% if !@values[:is_rp] %>
    <%= label_tag 'show_date', 'Date to Show This Repitition' %></br>
    <%= date_field_tag 'show_date', @values[:show_date] %></br></br>
  <% end %>
  <%= label_tag 'expiration_date', 'Date Habit Expires' %></br>
  <%= date_field_tag 'expiration_date', @values[:expiration_date] %></br></br>
  <%= label_tag 'reward', 'Reward' %><br>
  <%= number_field_tag 'reward', @values[:reward], min: 0 %></br></br>
  <%= label_tag 'penalty', 'Penalty' %><br>
  <%= number_field_tag 'penalty', @values[:penalty], min: 0 %></br></br>
  <%= label_tag 'parent_id', 'Habit\'s Parent' %></br>
  <%= select_tag 'parent_id', 
      options_from_collection_for_select(@activities,"id", "name",
					 @values[:parent_id].to_i),
      include_blank: true %></br></br>
  <%= label_tag 'report_to', "Report progress to" %></br>
  <%= select_tag 'report_to', options_for_select({ "Private" => "0", "Followers" => "1", 
						   "Mentors" => "2", "Both" => "3"}, 
						 @values[:report_to]) %></br></br>
  <%= hidden_field_tag 'type_group', 2 %>
  <%= submit_tag "Save Habit" %>
  <%= link_to "Cancel", today_path %>
<% end %>

app/views/activity_handler/_habit_form.html.erb
<%= form_tag(@path, method: @method, id: 'habit_form', class: @values[:type_group].to_i == 2 ? 'shown_form' : 'hidden_form') do %>
  <%= label_tag 'name', 'Habit Name' %><br>
  <%= text_field_tag 'name', @values[:name] %></br></br>
  <%= label_tag 'description', 'Habit Description' %><br>
  <%= text_area_tag 'description', @values[:description] %></br></br>
  <%= label_tag 'repeated', 'Days to Repeat' %><br>
  <% if @values[:repeated].nil?
       @values[:repeated] = []
     end
     days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
     days.map.with_index do |d, i| %>
    <%= check_box_tag "repeated[#{i}]", i, @values[:repeated].include?(i.to_s) %>
    <%= label_tag "repeated[#{i}]", d %>
  <% end %></br></br>
  <%= label_tag 'habit_type', "Required Completions to Get Reward" %></br>
  <%= radio_button_tag 'habit_type', 'number', @values[:habit_type] == "number" %>
  <%= number_field_tag 'total', @values[:total], min: 1 %>
  <%= label_tag 'total', " total" %></br>
  <%= radio_button_tag 'habit_type', 'week', @values[:habit_type] == "week" %>
  <%= number_field_tag 'per_week', @values[:per_week], min: 1 %>
  <%= label_tag 'per_week', " per week" %> 
  <%= label_tag 'weeks', " for " %>
  <%= number_field_tag 'weeks', @values[:weeks], min: 1 %>
  <%= label_tag 'weeks', " weeks" %></br>
  <%= radio_button_tag 'habit_type', 'none', @values[:habit_type] == "none" %>
  <%= label_tag 'none', "none (reward each completion)" %></br></br>
  <%= label_tag 'expiration_date', 'Date Habit Expires' %></br>
  <%= date_field_tag 'expiration_date', @values[:expiration_date] %></br></br>
  <%= label_tag 'period', 'Number of Days to Complete Each Instance of the Habit' %></br>
  <%= number_field_tag 'period', @values[:period], min: 1 %></br></br>
  <%= label_tag 'reward', 'Reward' %><br>
  <%= number_field_tag 'reward', @values[:reward], min: 0 %></br></br>
  <%= label_tag 'penalty', 'Penalty' %><br>
  <%= number_field_tag 'penalty', @values[:penalty], min: 0 %></br></br>
  <%= label_tag 'parent_id', 'Habit\'s Parent' %></br>
  <%= select_tag 'parent_id', 
      options_from_collection_for_select(@activities,"id", "name",
					 @values[:parent_id].to_i),
      include_blank: true %></br></br>
  <%= label_tag 'report_to', "Report progress to" %></br>
  <%= select_tag 'report_to', options_for_select({ "Private" => "0", "Followers" => "1", 
						   "Mentors" => "2", "Both" => "3"}, 
						 @values[:report_to]) %></br></br>
  <%= hidden_field_tag 'type_group', 2 %>
  <%= submit_tag "Save Habit" %>
  <%= link_to "Cancel", today_path %>
<% end %>

app/views/activity_handler/_task_form.html.erb
<%= form_tag(@path, method: @method, id: 'task_form', class: @values[:type_group].to_i == 1 ? 'shown_form' : 'hidden_form') do %>
  <%= label_tag 'name', 'Task Name' %><br>
  <%= text_field_tag 'name', @values[:name] %></br></br>
  <%= label_tag 'description', 'Task Description' %><br>
  <%= text_area_tag 'description', @values[:description] %></br></br>
  <%= label_tag 'show_date', 'Date to Show Task' %></br>
  <%= date_field_tag 'show_date', @values[:show_date] %></br></br>
  <%= label_tag 'expiration_date', 'Date to Task Expires' %></br>
  <%= date_field_tag 'expiration_date', @values[:expiration_date] %></br></br>
  <%= label_tag 'reward', 'Reward' %><br>
  <%= number_field_tag 'reward', @values[:reward], min: 0 %></br></br>
  <%= label_tag 'penalty', 'Penalty' %><br>
  <%= number_field_tag 'penalty', @values[:penalty], min: 0 %></br></br>
  <%= check_box_tag 'internal', "1", @values[:internal] == "1" %>
  <%= label_tag 'internal', 'Task is complete if children are' %><br></br>
  <%= label_tag 'parent_id', 'Task\'s Parent' %></br>
  <%= select_tag 'parent_id', 
      options_from_collection_for_select(@activities,"id", "name",
					 @values[:parent_id].to_i),
      include_blank: true %></br></br>
  <%= label_tag 'report_to', "Report progress to" %></br>
  <%= select_tag 'report_to', options_for_select({ "Private" => "0", "Followers" => "1", 
						   "Mentors" => "2", "Both" => "3"}, 
						 @values[:report_to]) %></br></br>
  <%= hidden_field_tag 'type_group', 1 %>
  <%= submit_tag "Save Task" %>
  <%= link_to "Cancel", today_path %>
<% end %>

app/views/activity_handler/_today_task.html.erb
<li class="task_item" id="task_<%= act.id %>"><%= check_box_tag "tasks[#{act.id}]", act.id, act.state == 1, class: 'task_checkbox'  %> <%= label_tag "tasks[#{act.id}]", act.name %> <span class="show-menu-marker" id="marker-<%= act.id %>">+</span></li>

app/views/activity_handler/destroy.js.erb
$("#task_<%= params[:id] %>").remove()

app/views/activity_handler/edit.html.erb
<h1>Edit Activity</h1>

<%= render 'edit_form' %>

app/views/activity_handler/new.html.erb
<h1>New Activity</h1>

<%= render 'form' %>

app/views/activity_handler/overview.html.erb
<h1>Overview</h1>
<% def self.print_act(act) %>
<li><%= link_to link_to act.name, controller: "activity_handler", action: "show", id: act.id %></li>
<ul>
<% act.children.each do |child|
    print_act(child)
   end%>
</ul>
<% end %>
<ul><% @roots.each do |root|
	 print_act(root)
       end%>
</ul>

app/views/activity_handler/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @activity.name  %>
  </br>
  <strong>Description:</strong>
  <%= @activity.description %>
  </br>
  <strong>Date:</strong>
  <%= @activity.show_date %>
  </br>
  <strong>Expiration Date:</strong>
  <%= @activity.expiration_date %>
  </br>
  <strong>Reward:</strong>
  <%= @activity.reward %>
  </br>
  <strong>Penalty:</strong>
  <%= @activity.penalty %>
  </br>
  <strong>Parent:</strong>
  <% if !@activity.parent.nil? %>
    <%= @activity.parent.name %>
  <% end %>
  </br>
  <strong>Children:</strong>
  <ul>
  <% @activity.children.each do |child| %>
    <li><%= child.name %></li>
  <% end %>
  </ul>
  <strong>Complete:</strong>
  <%= @activity.is_complete? %>
  </br>
</p>
<%= link_to "Back", today_path %> | <%= link_to "Edit", edit_activity_handler_path(@activity.id) %> | <%= link_to "Remove", activity_handler_path(@activity.id), method: :delete %>

app/views/activity_handler/toggle.js.erb
<% 
   act = Activity.find(params[:id])
   add_to = "today"
   if act.state == Activity::COMPLETE
     add_to = "complete"
   elsif act.state == Activity::OVERDUE 
     add_to = "overdue"
   end %>

$("#task_<%= act.id %>").remove();
$("<%= escape_javascript( render partial: 'today_task', object: Activity.find(params[:id]), as: 'act') %>").appendTo(".<%= add_to %>_tasks");

<% if !@notice.nil? %>
$(".alert_container").html("<div class=\"notice\"><%= @notice %></div>").show().delay(1800).fadeOut()
<% end %>

app/views/activity_handler/week.html.erb
<h1>Week Overview</h1>
<h2><%= link_to "<", :date => @days.keys[0].advance(:weeks => -1) %>
 Week of <%= @days.keys[0] %> <%= link_to ">", :date => @days.keys[0].advance(:weeks => 1) %></h2>
<% @days.each do |day, acts| %>
  <h3><%= day.to_s %></h3>
  <ul>
  <% acts.each do |act| %>
    <li><%= link_to act.name, controller: "activity_handler", action: "show", id: act.id %></li>
  <% end %>
  </ul>
<% end %>