config/routes.rb
Rails.application.routes.draw do

  get 'today' => 'activity_handler#today'
  get 'toggle/:id' => 'activity_handler#toggle'
  get 'week' => 'activity_handler#week'
  get 'overview' => 'activity_handler#overview'
  resources :activity_handler

  resources :users
  resources :sessions
  resources :friendships

  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "feed" => "users#feed", :as => "feed"

  root 'activity_handler#today'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessor :password, :password_confirmation

  before_save {  |user| user.email = email.downcase }
  before_save :encrypt_password
  before_create :create_remember_token

  has_one :activity_handler
  has_many :activities, :through =>:permissions
  has_many :permissions

  validates :password, presence: true, length: { minimum: 6 }, confirmation: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates(:email, presence: true, format: { with: VALID_EMAIL_REGEX},
            uniqueness: { case_sensitive: false } )

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(email, password)
    user = User.find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  private
  def create_remember_token
    self.remember_token = User.hash(User.new_remember_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include SessionsHelper, UsersHelper

  before_action :signed_in_user, only: [:edit,:update, :index]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :admin_user, only: [:index]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      add_ah @user
      Rails.logger.debug "#{DateTime.current} - #{@user.email} created an account"
      redirect_to root_url, :notice => "Signed Up!"
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user, :notice => "Profile Updated..."
    else
      render 'edit'
    end
  end

  def destroy
    user = User.find(params[:id])
    user.activity_handler.destroy
    user.permissions.where("level is ?", Permission::PRIVATE).each {|p| p.activity.destroy }
    user.permissions.destroy_all
    user.destroy
    Rails.logger.debug "#{DateTime.current} - #{user.email}'s account removed"
    redirect_to users_path, :notice => "User deleted."
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

    # Before filters
    def signed_in_user
      store_location
      redirect_to log_in_path, :notice => "Sign in required." unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_path unless current_user?(@user) || current_user.admin?
    end

    def admin_user
      if !current_user.admin?
        redirect_to root_path, :flash => { :notice => "You must be admin to do that" }
      end
    end

  
end

app/helpers/users_helper.rb
module UsersHelper

  def add_ah(user)
    date = Date.current
    sunday = date.end_of_week
    reset = sunday.advance(:weeks => 2)
    upto = sunday.advance(:weeks => 2)
    user.create_activity_handler :reset_date => reset, :upto_date => upto
  end
end

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explaination">
    <h2><%= pluralize(@user.errors.count, "error") %> 
      :</h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>

  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/feed.html.erb
<h1>Feed</h1>
<% @items.each do |item| %>
  <p><%= item.user.email %> - <%= item.message %></br>
    <%= item.created_at.to_formatted_s(:long) %>
  </p>
<% end %>

app/views/users/index.html.erb
<h1>All Users:</h1>
<% @users.each do |user| %>
<p><%= link_to user.email, user_path(user) %> | 
<%= link_to "delete", user_path(user), method: :delete,
	      data: { confirm: 'Are you sure?'} %></p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explaination">
    <h2><%= pluralize(@user.errors.count, "error") %> 
      :</h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>

  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/show.html.erb
<p>
  <strong>Email:</strong> 
  <%= @user.email %>
</p>

<strong>Following</strong>
<ul>
  <% for friendship in @user.friendships.where("kind is ?", Friendship::FOLLOWER) %>
    <li>
      <%=h friendship.friend.email %>
      (<%= link_to "remove", friendship, :method => :delete %>)
    </li>
  <% end %>
</ul>

<strong>Mentoring</strong>
<ul>
  <% for friendship in @user.friendships.where("kind is ?", Friendship::MENTOR) %>
    <li>
      <%=h friendship.friend.email %>
      (<%= link_to "remove", friendship, :method => :delete %>)
    </li>
  <% end %>
</ul>

<strong>Followed By</strong>
<ul>
  <% for friendship in @user.inverse_friendships.where("kind is ?", Friendship::FOLLOWER) %>
    <li>
      <%=h friendship.friend.email %>
      (<%= link_to "remove", friendship, :method => :delete %>)
    </li>
  <% end %>
</ul>


<%= link_to 'Home', root_path %> | <%= link_to 'Edit',
					edit_user_path(@user) %> | <%= link_to 'Add Friend', new_friendship_path %>